[build]
  command = "pnpm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20.0.0" }

[dev]
  framework = "vite"
  command = "pnpm run dev"
  port = 3000
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src * data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src 'self'; connect-src *"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[plugins]]
  package = "@netlify/plugin-vue"

[functions]
  directory = "netlify/functions"